### ISSUE TITLE
Improve accessibility and UX by using anchor tags for ListItem, rather than just click events

### ISSUE THREAD

**Issue by onebree** [Snakeyh/KeebMap#12]
By using on-click handlers and div elements for `ListItem`, I am unable to open in new tab from a right-click context menu. That is easier for me, than clicking to open _and focus to_ the new tab.

Furthermore, anchor tags would allow better keyboard navigation, which is key to accessibility. In fact, there is no keyboard navigation on the site, except to focus in search or your footer links.

This is a great resource, and I always recommend it to folks. LMK if you need any help implementing this!

**Comment by Snakeyh** [comment]
Thank you very much for submitting your issue, the latest commit should address your comments. Let me know if there any other improvements would improve your experience ✨

**Comment by onebree** [comment]
@Snakeyh TY for that commit! I am able to CTRL+Click for a new tab. However, keyboard navigation is still not the best. While it does focus on the anchor tags, there's no visual indicator of them being focused (aside from the lower left-hand corner showing the URL). You may want to add `:focus` and `:hover` styles to the anchor tags, along with any other pseudo classes for better UX.

Again, tysm for the commit!

**Comment by Snakeyh** [comment]
Chrome gave me a nice blue border but adding a `:focus` is definitely a better choice. Commited ✅ .

**Comment by onebree** [comment]
Ah, I use firefox and did not see that. Was more expecting the same styling as when you hover on the list items. TY for working on and replying to this quickly!
